### ISSUE TITLE
Building image for real Hardware.

### ISSUE THREAD

**Issue by ghalib210** [T-head-Semi/riscv-aosp#10]
Hello folks,

I want to build android OS to real RISC-V target Machine, can anyone help me out, How can build android OS.

Thanks in advance,
Ghalib khan c.

**Comment by peyo-hd** [comment]
Comment for other's reference.

Recently got physical hardware from https://www.aliexpress.com/item/1005003395978459.html
And build guidance in this repository was valid. Just with a few trimming.

My build steps here : https://github.com/android-risc-v/local_manifests

**Comment by m0jek** [comment]
> Comment for other's reference.
> 
> My build steps here : https://github.com/android-risc-v/local_manifests

I will give yours a try, my attempts have been failing using this repo ...

```
FAILED: ninja: 'device/thead/thead_ice910/ice910/system.prop', needed by 'out/target/product/ice910dk/obj/ETC/system_build_prop_intermediates/build.prop', missing and no known rule to make it
10:00:43 ninja failed with: exit status 1
```

**Comment by m0jek** [comment]
> Comment for other's reference.
> 
> Recently got physical hardware from https://www.aliexpress.com/item/1005003395978459.html And build guidance in this repository was valid. Just with a few trimming.
> 
> My build steps here : https://github.com/android-risc-v/local_manifests

Build works. 
Thank you.
Only the beginning, screen layout needs work and need to add a screen keyboard etc ...
