### ISSUE TITLE
Wifi and Bluetooth

### ISSUE THREAD

**Issue by m0jek** [T-head-Semi/riscv-aosp#11]
Anyone have the WiFI and Bluetooth drivers working on T-HEAD c910 ice hardware with Android ?

**Comment by MaoHan001** [comment]
The new development boards have get WiFI and Bluetooth drivers working on it but not RVB-ICE
https://beaglev-ahead.beagleboard.io/docs/latest/boards/beaglev/ahead/index.html
https://wiki.sipeed.com/licheepi4a
