### ISSUE TITLE
binder loop error

### ISSUE THREAD

**Issue by cghalibkhan** [T-head-Semi/riscv-aosp#12]
Hi,

I have build and trying to boot ramdisk. system & vendor images. while booting am hitting the following Error, can anyone resolve this issue to get till ADB shell.

[fu540_andriod-selinux-boot.log](https://github.com/T-head-Semi/riscv-aosp/files/8205002/fu540_andriod-selinux-boot.log)

**Comment by MaoHan001** [comment]
Fu540 is not a processor supported by T-Head. You can ask this question on https://lists.riscv.org/g/sig-android, where there are developers from other companies.
