### ISSUE TITLE
Is this project empty? 404 not found.

### ISSUE THREAD

**Issue by P0etry-rain** [T-head-Semi/riscv-aosp#13]
wget https://rosp-riscv.oss-cn-hangzhou.aliyuncs.com/prebuilts/android-emulator/linux-x86_64.zip
404 not found.

**Comment by MaoHan001** [comment]
Our prebuilts has been removed due to OSS access policy change, you can download new version prebuits from https://github.com/riscv-android-src/riscv-android

**Comment by P0etry-rain** [comment]
Okay, thank you for your help.
