### ISSUE TITLE
Download Prebuilt packages error

### ISSUE THREAD

**Issue by Xxfore** [T-head-Semi/riscv-aosp#14]
Is there any problem with oss buckets of https://rosp-riscv.oss-cn-hangzhou.aliyuncs.com/prebuilts/* ?
Seems it cant be access.
Thanks a lot.

**Comment by luyang00** [comment]
I have same issues about this...

**Comment by MaoHan001** [comment]
The precompiled version of Android 12 is no longer maintained on oss. You can go to https://github.com/riscv-android-src to get support for archived versions of 10/12 or refer to https://github.com/google/android-riscv64 for support related to AOSP mainline.
