### ISSUE TITLE
This repository is over its data quota

### ISSUE THREAD

**Issue by five-dimensional** [T-head-Semi/riscv-aosp#3]
$ git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/T-head-Semi/aosp-riscv.git/info/lfs'

**Comment by MaoHan001** [comment]
> $ git lfs pull
> batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> error: failed to fetch some objects from 'https://github.com/T-head-Semi/aosp-riscv.git/info/lfs'

I‘v move all the prebuilts files to our own oss，you can sync the git repository and download these files with the updated reproduce.sh script.

**Comment by MaoHan001** [comment]
The precompiled version of Android 12 is no longer maintained on oss. You can go to https://github.com/riscv-android-src to get support for archived versions of 10/12 or refer to https://github.com/google/android-riscv64 for support related to AOSP mainline.
