### ISSUE TITLE
Build failed!

### ISSUE THREAD

**Issue by unicornx** [T-head-Semi/riscv-aosp#5]
hi,  I tried to build and failed, error log attached, anybody else see the similar issue?
[error.log](https://github.com/T-head-Semi/aosp-riscv/files/5877486/error.log)

machine info, FYI:

LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**Comment by peyo-hd** [comment]
Hi @unicornx,
I tried to build,  and uploaded the patches to forked github repo - in different format.
Refer to README of https://github.com/android-rv/local_manifests

**Comment by unicornx** [comment]
closed this issue due to we have https://github.com/riscv-android-src now :)
