### ISSUE TITLE
reproduce.sh script is failing to clone sources.

### ISSUE THREAD

**Issue by ghalib210** [T-head-Semi/riscv-aosp#6]
Hello,

Am trying to reproduce build of aosp-riscv on x86 Machine, i have cloned https://github.com/T-head-Semi/aosp-riscv.git and run the reproduce script there it was failing to clone prebuilt sources as follows.

 Can any one know why this was happen and help me to resolve this issue.
 
$ ./reproduce.sh 
--2021-02-01 17:41:19--  https://rosp-riscv.oss-cn-hangzhou.aliyuncs.com/prebuilts/android-emulator/linux-x86_64.zip
Resolving rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)... failed: Name or service not known.
wget: unable to resolve host address ‘rosp-riscv.oss-cn-hangzhou.aliyuncs.com’
--2021-02-01 17:41:20--  https://rosp-riscv.oss-cn-hangzhou.aliyuncs.com/prebuilts/clang-tools/linux-x86.zip
Resolving rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)... failed: Name or service not known.
wget: unable to resolve host address ‘rosp-riscv.oss-cn-hangzhou.aliyuncs.com’
--2021-02-01 17:41:20--  https://rosp-riscv.oss-cn-hangzhou.aliyuncs.com/prebuilts/clang/host/linux-x86/clang-dev.zip
Resolving rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)... failed: Name or service not known.
wget: unable to resolve host address ‘rosp-riscv.oss-cn-hangzhou.aliyuncs.com’
--2021-02-01 17:41:20--  https://rosp-riscv.oss-cn-hangzhou.aliyuncs.com/prebuilts/gcc/linux-x86/riscv64/riscv64.zip
Resolving rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)... failed: Name or service not known.
wget: unable to resolve host address ‘rosp-riscv.oss-cn-hangzhou.aliyuncs.com’
--2021-02-01 17:41:20--  https://rosp-riscv.oss-cn-hangzhou.aliyuncs.com/prebuilts/misc/riscv64.zip
Resolving rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)... failed: Name or service not known.
wget: unable to resolve host address ‘rosp-riscv.oss-cn-hangzhou.aliyuncs.com’
--2021-02-01 17:41:20--  https://rosp-riscv.oss-cn-hangzhou.aliyuncs.com/prebuilts/ndk/r20.zip
Resolving rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)... failed: Name or service not known.
wget: unable to resolve host address ‘rosp-riscv.oss-cn-hangzhou.aliyuncs.com’
--2021-02-01 17:41:20--  https://rosp-riscv.oss-cn-hangzhou.aliyuncs.com/prebuilts/qemu-kernel/riscv64.zip
Resolving rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)... failed: Name or service not known.
wget: unable to resolve host address ‘rosp-riscv.oss-cn-hangzhou.aliyuncs.com’
--2021-02-01 17:41:20--  https://rosp-riscv.oss-cn-hangzhou.aliyuncs.com/prebuilts/vndk/v28/riscv64.zip
Resolving rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)... failed: Name or service not known.
wget: unable to resolve host address ‘rosp-riscv.oss-cn-hangzhou.aliyuncs.com’

Thanks in advance.
Ghalib khan.

**Comment by pathakraul** [comment]
Same issue here.

Resolving rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)... 118.31.219.197
Connecting to rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)|118.31.219.197|:443... connected.
Unable to establish SSL connection.

**Comment by pratikfarkase94** [comment]
> Same issue here.
> 
> Resolving rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)... 118.31.219.197
> Connecting to rosp-riscv.oss-cn-hangzhou.aliyuncs.com (rosp-riscv.oss-cn-hangzhou.aliyuncs.com)|118.31.219.197|:443... connected.
> Unable to establish SSL connection.

Hi Rahul, can help you out. have downloaded and built successfully after a lot of effort. email me: pratikfarkase94@gmail.com

**Comment by ghalib210** [comment]
I have resolved this by downloading it manually as follows,

By multiple time's running **download_prebuilts.sh** script as mentiond in reproduce.sh file from  /script/ path as follows, download was successful.

#download prebuilts |  
-- | --
  | if [ ! -f ${AOSP_RISCV_TOP}/stages/.stamp_download_pre ]; then
  | ${AOSP_RISCV_TOP}/script/download_prebuilts.sh
  | touch ${AOSP_RISCV_TOP}/stages/.stamp_download_pre
  | fi
