### ISSUE TITLE
android10-release sources from https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/manifest URL failing to download.

### ISSUE THREAD

**Issue by ghalib210** [T-head-Semi/riscv-aosp#8]
I was facing an issue while downloading android10 sources from https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/manifest URL as follow's,

$ cd ${AOSP_RISCV_BUILD_TOP}
**$ repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/manifest -b android10-release**

error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received. 
fatal: The remote end hung up unexpectedly 
fatal: early EOF 
fatal: index-pack failed 

platform/prebuilts/misc: 
remote: Counting objects: 1582, done.         
remote: Compressing objects: 100% (1118/1118), done.         
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received. 
fatal: The remote end hung up unexpectedly 
fatal: early EOF 
fatal: index-pack failed 
 
remote: Counting objects: 1582, done.        MiB | 44.00 KiB/s     
remote: Compressing objects: 100% (1118/1118), done.         
remote: Total 12081 (delta 6032), reused 10083 (delta 5385)         
Receiving objects: 100% (12081/12081), 108.40 MiB | 55.00 KiB/s, done. 
Resolving deltas: 100% (6032/6032), done. 
remote: Counting objects: 25, done.        7 MiB | 74.00 KiB/s    objects:  96% (9959/10289), 821.60 MiB | 86.00 KiB/s    
remote: Compressing objects: 100% (20/20), done.         
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received. 
fatal: The remote end hung up unexpectedly 
fatal: early EOF 
fatal: index-pack failed 

platform/prebuilts/misc: 
remote: Counting objects: 1582, done.         
remote: Compressing objects: 100% (1118/1118), done.         
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received. 
fatal: The remote end hung up unexpectedly 
fatal: early EOF 
fatal: index-pack failed 

Can any one help me out to reslove this issue.

Thanks in advance
Ghalib khan.

**Comment by nelson-xia** [comment]
try again. you had better use sync -j1.  It takes me a few days to get the whole codebase.

**Comment by ghalib210** [comment]
Hello nelson,

I have kept it for 4 day's but still it's in loop. what to do?.

**Comment by nelson-xia** [comment]
Copy from Google's comments:

More rarely, Linux clients experience connectivity issues, getting stuck in the middle of downloads (typically during receiving objects). It's been reported that tweaking the settings of the TCP/IP stack and using non-parallel commands can improve the situation. You need root access to modify the TCP setting:


sudo sysctl -w net.ipv4.tcp_window_scaling=0
repo sync -j1

I have tried the first command, but I still come across the same problem. Maybe you can try it.

**Comment by ghalib210** [comment]
Thank you nelson-xia, i was able to clone the sources as you suggested, even if we use repo sync with -j1 few are failing, so one more think is we have to use dedicated line of network.

with this, i was able to clone and build the sources. Thanks a lot one more time. 

Now am going to start working on real target machine. Can you help me out how to build for real target machine, i'll do one think i'll create a new thread for this, it will own't create conflict.
