### ISSUE TITLE
Emulator failing once it Lunched.

### ISSUE THREAD

**Issue by ghalib210** [T-head-Semi/riscv-aosp#9]
Hello,

I have cloned and build aosp-riscv, Currently there was 2 issues like, 

1. when i lunch emulator it's failing and throwing an Error as follows,

$ emulator -selinux permissive -qemu -smp 2 -m 3800M -bios /home/performance-server/ghalib-khan/android/aosp-riscv/aosp-riscv/aosp/prebuilts/qemu-kernel/riscv64/ranchu/fw_jump.bin
emulator: WARNING: encryption is off
emulator: ERROR: VkCommonOperations.cpp:537: Failed to create Vulkan instance.
ProbeKVM: This user doesn't have permissions to use KVM (/dev/kvm).
The KVM line in /etc/group is: [LINE_NOT_FOUND]

If the current user has KVM permissions,
the KVM line in /etc/group should end with ":" followed by your username.

If we see LINE_NOT_FOUND, the kvm group may need to be created along with permissions:
    sudo groupadd -r kvm
    # Then ensure /lib/udev/rules.d/50-udev-default.rules contains something like:
    # KERNEL=="kvm", GROUP="kvm", MODE="0660"
    # and then run:
    sudo gpasswd -a $USER kvm

If we see kvm:... but no username at the end, running the following command may allow KVM access:
    sudo gpasswd -a $USER kvm

You may need to log out and back in for changes to take effect.

kernel@80200000, initrd@88200000
qemu-system-riscv64: plic: invalid register write: 000001fc
qemu-system-riscv64: plic: invalid register read: 00002090
qemu-system-riscv64: plic: invalid register write: 00002090
qemu-system-riscv64: plic: invalid register read: 00002190
qemu-system-riscv64: plic: invalid register write: 00002190
**Segmentation fault (core dumped)**

2. In Emulator Graphical thinks are not visible.

Can any help me out resolve this issue.

Thanks in advance,
Ghalib khan c.

**Comment by ghalib210** [comment]
Here i have resolved few thinks as follows,

**emulator: ERROR: VkCommonOperations.cpp:537: Failed to create Vulkan instance.** 
$ sudo apt-get install mesa-vulkan-drivers 

**ProbeKVM: This user doesn't have permissions to use KVM (/dev/kvm).** 
$ sudo chown performance-server /dev/kvm 

**emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037** 
$ adb start-server 
* daemon not running; starting now at tcp:5037 
* daemon started successfully 

After this, when i lunch Emulator it started but stay at the **blank screen with android log** and show below invalid register read & write,

$ emulator -selinux permissive -qemu -smp 2 -m 3800M -bios /home/performance-serve
r/ghalib-khan/android/aosp-riscv/aosp-riscv/aosp/prebuilts/qemu-kernel/riscv64/ranchu/fw_jump.bin
emulator: WARNING: encryption is off
kernel@80200000, initrd@88200000
qemu-system-riscv64: plic: invalid register write: 000001fc
qemu-system-riscv64: plic: invalid register read: 00002090
qemu-system-riscv64: plic: invalid register write: 00002090
qemu-system-riscv64: plic: invalid register read: 00002190
qemu-system-riscv64: plic: invalid register write: 00002190
Segmentation fault (core dumped)

![GetImage](https://user-images.githubusercontent.com/66322809/108019270-e27c9c80-703f-11eb-9d6d-c41b49b63222.png)

**Comment by MaoHan001** [comment]
The new version has replaced the goldfish emulator with cuttlefish. You can refer to it to get more information：
https://github.com/google/android-riscv64
